apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiYVhaaGJtOTJMbUV1ZGtCdFpTNWpiMjA2WjJod1gxRlZOMmRIYzBReE9WQjRVVXhXUmtOamRWUXdkMUI1UTBjeVMwdHVkREY0Ylc5R09RPT0iCiAgICAgICAgICAgICAgICB9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fSwKCQkiaHViLnRvbnNjcmVhdGl2ZS5ydSI6IHt9Cgl9LAoJImNyZWRzU3RvcmUiOiAib3N4a2V5Y2hhaW4iLAoJImN1cnJlbnRDb250ZXh0IjogIm9yYnN0YWNrIiwKCSJwbHVnaW5zIjogewoJCSIteC1jbGktaGludHMiOiB7CgkJCSJlbmFibGVkIjogInRydWUiCgkJfSwKCQkiZGVidWciOiB7CgkJCSJob29rcyI6ICJleGVjIgoJCX0sCgkJInNjb3V0IjogewoJCQkiaG9va3MiOiAicHVsbCxidWlsZHggYnVpbGQiCgkJfQoJfSwKCSJmZWF0dXJlcyI6IHsKCQkiaG9va3MiOiAidHJ1ZSIKCX0KfQo=
type: kubernetes.io/dockerconfigjson
